[tool.poetry]
name = "dutchpoliticalfacebookadcomparision"
version = "1"
description = ""
authors = ["Joren Vrancken"]

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.0.1"
peewee = "^3.14.4"
requests = "^2.26.0"
spacy = "^3.1.2"
Unidecode = "^1.2.0"

[tool.poetry.dev-dependencies]
pydocstyle = {extras = ["toml"], version = "^6.1.1"}
black = "^21.7b0"
flake8 = "^3.9.2"
isort = "^5.9.3"

[tool.isort]
profile = "black"
multi_line_output = 3
known_first_party = "constants, models, parsing, utils"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
