[tool.poetry]
name = "dutchpoliticalfacebookadcomparision"
version = "1"
description = ""
authors = ["Joren Vrancken"]

[tool.poetry.dependencies]
python = "^3.9"
Jinja2 = "^3.0.1"
peewee = "^3.14.4"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pydocstyle = "^6.1.1"
flake8 = "^3.9.2"
flake8-import-order = "^0.18.1"
black = "^21.6b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
