[tool.poetry]
name = "dutchpoliticalfacebookadcomparision"
version = "1"
description = ""
authors = ["Joren Vrancken"]

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.1"
peewee = "^3.14.10"
requests = "^2.27.1"
spacy = "^3.2.4"
Unidecode = "^1.3.4"
pandas = "^1.4.3"
matplotlib = "^3.5.2"
jupyter = "^1.0.0"

[tool.poetry.dev-dependencies]
pydocstyle = "^6.1.1"
black = "^22.3.0"
flake8 = "^4.0.1"
isort = "^5.10.1"

[tool.isort]
profile = "black"
multi_line_output = 3
known_first_party = "constants, models, parsing, themes, utils"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
