---

name: "Linting"
on: "push"

jobs:
  lint:
    name: "Linting"
    runs-on: "ubuntu-latest"
    steps:

      - name: "Checkout the repository"
        uses: "actions/checkout@v2"

      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.10'

      - name: "Install Poetry"
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: "Run Black"
        run: "poetry run black --quiet --check ."

      - name: "Run PyDocStyle"
        run: "poetry run pydocstyle --add-ignore=D100,D104"
